### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by adm-michal** [talvasconcelos/cms-bot#3]
The installation went without problems, but when I try to start the program the following error appears:

```
> cms-bot@1.0.0 start /cms-bot
> node index.js

internal/fs/utils.js:230
    throw err;
    ^

Error: ENOENT: no such file or directory, open './logs/log.json'
    at Object.openSync (fs.js:457:3)
    at writeFileSync (fs.js:1282:35)
    at FileSync.read (/cms-bot/node_modules/lowdb/adapters/FileSync.js:46:9)
    at LodashWrapper.db.read (/cms-bot/node_modules/lowdb/lib/main.js:32:21)
    at module.exports (/cms-bot/node_modules/lowdb/lib/main.js:51:13)
    at Object.<anonymous> (/cms-bot/logger.js:5:12)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/cms-bot/trader.js:3:12)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/cms-bot/strategies/microtrades.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './logs/log.json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cms-bot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cms-bot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2020-02-19T11_51_28_554Z-debug.log

```

**Comment by talvasconcelos** [comment]
It was missing the logs folder!! Sorry about that, it should be fixed with the new commit! 

Make a git pull and npm install again
